# Generated by Django 2.0.3 on 2018-04-01 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(default='', max_length=32, verbose_name='昵称')),
                ('phone', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='手机号')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=8, verbose_name='性别')),
                ('birth', models.DateField(auto_now_add=True, null=True, verbose_name='生日')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='头像')),
                ('info', models.TextField(blank=True, default='', null=True, verbose_name='个人简介')),
                ('people', models.ForeignKey(blank=True, null=True, on_delete=False, to='grade.People')),
                ('user', models.OneToOneField(on_delete=False, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
